version: '3'
services:
    web:
        build: .
        ports:
            - 80:80
        volumes:
            - ../source:/var/www/html
        links:
            - db
    db:
        build: .
        image: mariadb:10.1
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: dockerweb
            MYSQL_USER: dockerweb
            MYSQL_PASSWORD: dockerweb
            MYSQL_ROOT_PASSWORD: root